# Generated by Django 5.1.1 on 2024-09-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemaluguel',
            options={'verbose_name': 'Item Aluguel', 'verbose_name_plural': 'Itens Aluguel'},
        ),
    ]
