# Generated by Django 5.1.1 on 2024-09-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_itemaluguel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemaluguel',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
