# Generated by Django 5.1.1 on 2024-09-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_aluguel_valor_itemaluguel_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='valor',
        ),
    ]
