# Generated by Django 5.1.1 on 2024-09-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
