# Generated by Django 5.1.1 on 2024-09-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_publico_filme_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='classificação_etaria',
            new_name='classificacao_etaria',
        ),
    ]
