# Generated by Django 5.1.1 on 2024-09-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_rename_classificação_etaria_filme_classificacao_etaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano_lancamento',
            field=models.PositiveIntegerField(default=1900),
        ),
    ]
